# Generated by Django 5.0.7 on 2024-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_buildingtype_slug_alter_buildingtype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='сountrie',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
