# Generated by Django 5.0.7 on 2024-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_сountrie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
