# Generated by Django 5.0.7 on 2024-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_region_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='abbreviations',
            field=models.CharField(default=None, help_text='Абривиатура', max_length=10),
        ),
    ]
