# Generated by Django 5.0.7 on 2024-08-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_region_abbreviations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сountrie',
            new_name='Countrie',
        ),
    ]
